# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/Luftmysza/Nowy/ZadKcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/Luftmysza/Nowy/ZadKcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/Luftmysza/Nowy/ZadKcpp/CMakeFiles /run/media/Luftmysza/Nowy/ZadKcpp/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/Luftmysza/Nowy/ZadKcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ZadZwracanie

# Build rule for target.
ZadZwracanie: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadZwracanie
.PHONY : ZadZwracanie

# fast build rule for target.
ZadZwracanie/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadZwracanie.dir/build.make CMakeFiles/ZadZwracanie.dir/build
.PHONY : ZadZwracanie/fast

#=============================================================================
# Target rules for targets named ZadAdresowaniePamieci

# Build rule for target.
ZadAdresowaniePamieci: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadAdresowaniePamieci
.PHONY : ZadAdresowaniePamieci

# fast build rule for target.
ZadAdresowaniePamieci/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadAdresowaniePamieci.dir/build.make CMakeFiles/ZadAdresowaniePamieci.dir/build
.PHONY : ZadAdresowaniePamieci/fast

#=============================================================================
# Target rules for targets named ZadArytmetykaWskaznikow

# Build rule for target.
ZadArytmetykaWskaznikow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadArytmetykaWskaznikow
.PHONY : ZadArytmetykaWskaznikow

# fast build rule for target.
ZadArytmetykaWskaznikow/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadArytmetykaWskaznikow.dir/build.make CMakeFiles/ZadArytmetykaWskaznikow.dir/build
.PHONY : ZadArytmetykaWskaznikow/fast

#=============================================================================
# Target rules for targets named ZadBin2Dec

# Build rule for target.
ZadBin2Dec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadBin2Dec
.PHONY : ZadBin2Dec

# fast build rule for target.
ZadBin2Dec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadBin2Dec.dir/build.make CMakeFiles/ZadBin2Dec.dir/build
.PHONY : ZadBin2Dec/fast

#=============================================================================
# Target rules for targets named ZadCinCoutFile

# Build rule for target.
ZadCinCoutFile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadCinCoutFile
.PHONY : ZadCinCoutFile

# fast build rule for target.
ZadCinCoutFile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadCinCoutFile.dir/build.make CMakeFiles/ZadCinCoutFile.dir/build
.PHONY : ZadCinCoutFile/fast

#=============================================================================
# Target rules for targets named ZadDec2Bin

# Build rule for target.
ZadDec2Bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadDec2Bin
.PHONY : ZadDec2Bin

# fast build rule for target.
ZadDec2Bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadDec2Bin.dir/build.make CMakeFiles/ZadDec2Bin.dir/build
.PHONY : ZadDec2Bin/fast

#=============================================================================
# Target rules for targets named ZadPrzekazywanieTablic

# Build rule for target.
ZadPrzekazywanieTablic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadPrzekazywanieTablic
.PHONY : ZadPrzekazywanieTablic

# fast build rule for target.
ZadPrzekazywanieTablic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPrzekazywanieTablic.dir/build.make CMakeFiles/ZadPrzekazywanieTablic.dir/build
.PHONY : ZadPrzekazywanieTablic/fast

#=============================================================================
# Target rules for targets named ZadIq

# Build rule for target.
ZadIq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadIq
.PHONY : ZadIq

# fast build rule for target.
ZadIq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadIq.dir/build.make CMakeFiles/ZadIq.dir/build
.PHONY : ZadIq/fast

#=============================================================================
# Target rules for targets named ZadMainExample

# Build rule for target.
ZadMainExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadMainExample
.PHONY : ZadMainExample

# fast build rule for target.
ZadMainExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadMainExample.dir/build.make CMakeFiles/ZadMainExample.dir/build
.PHONY : ZadMainExample/fast

#=============================================================================
# Target rules for targets named ZadPetle

# Build rule for target.
ZadPetle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadPetle
.PHONY : ZadPetle

# fast build rule for target.
ZadPetle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPetle.dir/build.make CMakeFiles/ZadPetle.dir/build
.PHONY : ZadPetle/fast

#=============================================================================
# Target rules for targets named ZadSwitch

# Build rule for target.
ZadSwitch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadSwitch
.PHONY : ZadSwitch

# fast build rule for target.
ZadSwitch/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadSwitch.dir/build.make CMakeFiles/ZadSwitch.dir/build
.PHONY : ZadSwitch/fast

#=============================================================================
# Target rules for targets named ZadPriorytetyOperatorow

# Build rule for target.
ZadPriorytetyOperatorow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadPriorytetyOperatorow
.PHONY : ZadPriorytetyOperatorow

# fast build rule for target.
ZadPriorytetyOperatorow/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPriorytetyOperatorow.dir/build.make CMakeFiles/ZadPriorytetyOperatorow.dir/build
.PHONY : ZadPriorytetyOperatorow/fast

#=============================================================================
# Target rules for targets named ZadUnia

# Build rule for target.
ZadUnia: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadUnia
.PHONY : ZadUnia

# fast build rule for target.
ZadUnia/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadUnia.dir/build.make CMakeFiles/ZadUnia.dir/build
.PHONY : ZadUnia/fast

#=============================================================================
# Target rules for targets named ZadWywolanieFunkcji

# Build rule for target.
ZadWywolanieFunkcji: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZadWywolanieFunkcji
.PHONY : ZadWywolanieFunkcji

# fast build rule for target.
ZadWywolanieFunkcji/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadWywolanieFunkcji.dir/build.make CMakeFiles/ZadWywolanieFunkcji.dir/build
.PHONY : ZadWywolanieFunkcji/fast

src/ZadAdresowaniePamieci.o: src/ZadAdresowaniePamieci.cc.o

.PHONY : src/ZadAdresowaniePamieci.o

# target to build an object file
src/ZadAdresowaniePamieci.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadAdresowaniePamieci.dir/build.make CMakeFiles/ZadAdresowaniePamieci.dir/src/ZadAdresowaniePamieci.cc.o
.PHONY : src/ZadAdresowaniePamieci.cc.o

src/ZadAdresowaniePamieci.i: src/ZadAdresowaniePamieci.cc.i

.PHONY : src/ZadAdresowaniePamieci.i

# target to preprocess a source file
src/ZadAdresowaniePamieci.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadAdresowaniePamieci.dir/build.make CMakeFiles/ZadAdresowaniePamieci.dir/src/ZadAdresowaniePamieci.cc.i
.PHONY : src/ZadAdresowaniePamieci.cc.i

src/ZadAdresowaniePamieci.s: src/ZadAdresowaniePamieci.cc.s

.PHONY : src/ZadAdresowaniePamieci.s

# target to generate assembly for a file
src/ZadAdresowaniePamieci.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadAdresowaniePamieci.dir/build.make CMakeFiles/ZadAdresowaniePamieci.dir/src/ZadAdresowaniePamieci.cc.s
.PHONY : src/ZadAdresowaniePamieci.cc.s

src/ZadArytmetykaWskaznikow.o: src/ZadArytmetykaWskaznikow.cc.o

.PHONY : src/ZadArytmetykaWskaznikow.o

# target to build an object file
src/ZadArytmetykaWskaznikow.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadArytmetykaWskaznikow.dir/build.make CMakeFiles/ZadArytmetykaWskaznikow.dir/src/ZadArytmetykaWskaznikow.cc.o
.PHONY : src/ZadArytmetykaWskaznikow.cc.o

src/ZadArytmetykaWskaznikow.i: src/ZadArytmetykaWskaznikow.cc.i

.PHONY : src/ZadArytmetykaWskaznikow.i

# target to preprocess a source file
src/ZadArytmetykaWskaznikow.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadArytmetykaWskaznikow.dir/build.make CMakeFiles/ZadArytmetykaWskaznikow.dir/src/ZadArytmetykaWskaznikow.cc.i
.PHONY : src/ZadArytmetykaWskaznikow.cc.i

src/ZadArytmetykaWskaznikow.s: src/ZadArytmetykaWskaznikow.cc.s

.PHONY : src/ZadArytmetykaWskaznikow.s

# target to generate assembly for a file
src/ZadArytmetykaWskaznikow.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadArytmetykaWskaznikow.dir/build.make CMakeFiles/ZadArytmetykaWskaznikow.dir/src/ZadArytmetykaWskaznikow.cc.s
.PHONY : src/ZadArytmetykaWskaznikow.cc.s

src/ZadBin2Dec.o: src/ZadBin2Dec.cc.o

.PHONY : src/ZadBin2Dec.o

# target to build an object file
src/ZadBin2Dec.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadBin2Dec.dir/build.make CMakeFiles/ZadBin2Dec.dir/src/ZadBin2Dec.cc.o
.PHONY : src/ZadBin2Dec.cc.o

src/ZadBin2Dec.i: src/ZadBin2Dec.cc.i

.PHONY : src/ZadBin2Dec.i

# target to preprocess a source file
src/ZadBin2Dec.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadBin2Dec.dir/build.make CMakeFiles/ZadBin2Dec.dir/src/ZadBin2Dec.cc.i
.PHONY : src/ZadBin2Dec.cc.i

src/ZadBin2Dec.s: src/ZadBin2Dec.cc.s

.PHONY : src/ZadBin2Dec.s

# target to generate assembly for a file
src/ZadBin2Dec.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadBin2Dec.dir/build.make CMakeFiles/ZadBin2Dec.dir/src/ZadBin2Dec.cc.s
.PHONY : src/ZadBin2Dec.cc.s

src/ZadCinCoutFile.o: src/ZadCinCoutFile.cc.o

.PHONY : src/ZadCinCoutFile.o

# target to build an object file
src/ZadCinCoutFile.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadCinCoutFile.dir/build.make CMakeFiles/ZadCinCoutFile.dir/src/ZadCinCoutFile.cc.o
.PHONY : src/ZadCinCoutFile.cc.o

src/ZadCinCoutFile.i: src/ZadCinCoutFile.cc.i

.PHONY : src/ZadCinCoutFile.i

# target to preprocess a source file
src/ZadCinCoutFile.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadCinCoutFile.dir/build.make CMakeFiles/ZadCinCoutFile.dir/src/ZadCinCoutFile.cc.i
.PHONY : src/ZadCinCoutFile.cc.i

src/ZadCinCoutFile.s: src/ZadCinCoutFile.cc.s

.PHONY : src/ZadCinCoutFile.s

# target to generate assembly for a file
src/ZadCinCoutFile.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadCinCoutFile.dir/build.make CMakeFiles/ZadCinCoutFile.dir/src/ZadCinCoutFile.cc.s
.PHONY : src/ZadCinCoutFile.cc.s

src/ZadDec2Bin.o: src/ZadDec2Bin.cc.o

.PHONY : src/ZadDec2Bin.o

# target to build an object file
src/ZadDec2Bin.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadDec2Bin.dir/build.make CMakeFiles/ZadDec2Bin.dir/src/ZadDec2Bin.cc.o
.PHONY : src/ZadDec2Bin.cc.o

src/ZadDec2Bin.i: src/ZadDec2Bin.cc.i

.PHONY : src/ZadDec2Bin.i

# target to preprocess a source file
src/ZadDec2Bin.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadDec2Bin.dir/build.make CMakeFiles/ZadDec2Bin.dir/src/ZadDec2Bin.cc.i
.PHONY : src/ZadDec2Bin.cc.i

src/ZadDec2Bin.s: src/ZadDec2Bin.cc.s

.PHONY : src/ZadDec2Bin.s

# target to generate assembly for a file
src/ZadDec2Bin.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadDec2Bin.dir/build.make CMakeFiles/ZadDec2Bin.dir/src/ZadDec2Bin.cc.s
.PHONY : src/ZadDec2Bin.cc.s

src/ZadIq.o: src/ZadIq.cc.o

.PHONY : src/ZadIq.o

# target to build an object file
src/ZadIq.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadIq.dir/build.make CMakeFiles/ZadIq.dir/src/ZadIq.cc.o
.PHONY : src/ZadIq.cc.o

src/ZadIq.i: src/ZadIq.cc.i

.PHONY : src/ZadIq.i

# target to preprocess a source file
src/ZadIq.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadIq.dir/build.make CMakeFiles/ZadIq.dir/src/ZadIq.cc.i
.PHONY : src/ZadIq.cc.i

src/ZadIq.s: src/ZadIq.cc.s

.PHONY : src/ZadIq.s

# target to generate assembly for a file
src/ZadIq.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadIq.dir/build.make CMakeFiles/ZadIq.dir/src/ZadIq.cc.s
.PHONY : src/ZadIq.cc.s

src/ZadMainExample.o: src/ZadMainExample.cc.o

.PHONY : src/ZadMainExample.o

# target to build an object file
src/ZadMainExample.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadMainExample.dir/build.make CMakeFiles/ZadMainExample.dir/src/ZadMainExample.cc.o
.PHONY : src/ZadMainExample.cc.o

src/ZadMainExample.i: src/ZadMainExample.cc.i

.PHONY : src/ZadMainExample.i

# target to preprocess a source file
src/ZadMainExample.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadMainExample.dir/build.make CMakeFiles/ZadMainExample.dir/src/ZadMainExample.cc.i
.PHONY : src/ZadMainExample.cc.i

src/ZadMainExample.s: src/ZadMainExample.cc.s

.PHONY : src/ZadMainExample.s

# target to generate assembly for a file
src/ZadMainExample.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadMainExample.dir/build.make CMakeFiles/ZadMainExample.dir/src/ZadMainExample.cc.s
.PHONY : src/ZadMainExample.cc.s

src/ZadPetle.o: src/ZadPetle.cc.o

.PHONY : src/ZadPetle.o

# target to build an object file
src/ZadPetle.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPetle.dir/build.make CMakeFiles/ZadPetle.dir/src/ZadPetle.cc.o
.PHONY : src/ZadPetle.cc.o

src/ZadPetle.i: src/ZadPetle.cc.i

.PHONY : src/ZadPetle.i

# target to preprocess a source file
src/ZadPetle.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPetle.dir/build.make CMakeFiles/ZadPetle.dir/src/ZadPetle.cc.i
.PHONY : src/ZadPetle.cc.i

src/ZadPetle.s: src/ZadPetle.cc.s

.PHONY : src/ZadPetle.s

# target to generate assembly for a file
src/ZadPetle.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPetle.dir/build.make CMakeFiles/ZadPetle.dir/src/ZadPetle.cc.s
.PHONY : src/ZadPetle.cc.s

src/ZadPriorytetyOperatorow.o: src/ZadPriorytetyOperatorow.cc.o

.PHONY : src/ZadPriorytetyOperatorow.o

# target to build an object file
src/ZadPriorytetyOperatorow.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPriorytetyOperatorow.dir/build.make CMakeFiles/ZadPriorytetyOperatorow.dir/src/ZadPriorytetyOperatorow.cc.o
.PHONY : src/ZadPriorytetyOperatorow.cc.o

src/ZadPriorytetyOperatorow.i: src/ZadPriorytetyOperatorow.cc.i

.PHONY : src/ZadPriorytetyOperatorow.i

# target to preprocess a source file
src/ZadPriorytetyOperatorow.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPriorytetyOperatorow.dir/build.make CMakeFiles/ZadPriorytetyOperatorow.dir/src/ZadPriorytetyOperatorow.cc.i
.PHONY : src/ZadPriorytetyOperatorow.cc.i

src/ZadPriorytetyOperatorow.s: src/ZadPriorytetyOperatorow.cc.s

.PHONY : src/ZadPriorytetyOperatorow.s

# target to generate assembly for a file
src/ZadPriorytetyOperatorow.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPriorytetyOperatorow.dir/build.make CMakeFiles/ZadPriorytetyOperatorow.dir/src/ZadPriorytetyOperatorow.cc.s
.PHONY : src/ZadPriorytetyOperatorow.cc.s

src/ZadPrzekazywanieTablic.o: src/ZadPrzekazywanieTablic.cc.o

.PHONY : src/ZadPrzekazywanieTablic.o

# target to build an object file
src/ZadPrzekazywanieTablic.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPrzekazywanieTablic.dir/build.make CMakeFiles/ZadPrzekazywanieTablic.dir/src/ZadPrzekazywanieTablic.cc.o
.PHONY : src/ZadPrzekazywanieTablic.cc.o

src/ZadPrzekazywanieTablic.i: src/ZadPrzekazywanieTablic.cc.i

.PHONY : src/ZadPrzekazywanieTablic.i

# target to preprocess a source file
src/ZadPrzekazywanieTablic.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPrzekazywanieTablic.dir/build.make CMakeFiles/ZadPrzekazywanieTablic.dir/src/ZadPrzekazywanieTablic.cc.i
.PHONY : src/ZadPrzekazywanieTablic.cc.i

src/ZadPrzekazywanieTablic.s: src/ZadPrzekazywanieTablic.cc.s

.PHONY : src/ZadPrzekazywanieTablic.s

# target to generate assembly for a file
src/ZadPrzekazywanieTablic.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadPrzekazywanieTablic.dir/build.make CMakeFiles/ZadPrzekazywanieTablic.dir/src/ZadPrzekazywanieTablic.cc.s
.PHONY : src/ZadPrzekazywanieTablic.cc.s

src/ZadSwitch.o: src/ZadSwitch.cc.o

.PHONY : src/ZadSwitch.o

# target to build an object file
src/ZadSwitch.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadSwitch.dir/build.make CMakeFiles/ZadSwitch.dir/src/ZadSwitch.cc.o
.PHONY : src/ZadSwitch.cc.o

src/ZadSwitch.i: src/ZadSwitch.cc.i

.PHONY : src/ZadSwitch.i

# target to preprocess a source file
src/ZadSwitch.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadSwitch.dir/build.make CMakeFiles/ZadSwitch.dir/src/ZadSwitch.cc.i
.PHONY : src/ZadSwitch.cc.i

src/ZadSwitch.s: src/ZadSwitch.cc.s

.PHONY : src/ZadSwitch.s

# target to generate assembly for a file
src/ZadSwitch.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadSwitch.dir/build.make CMakeFiles/ZadSwitch.dir/src/ZadSwitch.cc.s
.PHONY : src/ZadSwitch.cc.s

src/ZadUnia.o: src/ZadUnia.cc.o

.PHONY : src/ZadUnia.o

# target to build an object file
src/ZadUnia.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadUnia.dir/build.make CMakeFiles/ZadUnia.dir/src/ZadUnia.cc.o
.PHONY : src/ZadUnia.cc.o

src/ZadUnia.i: src/ZadUnia.cc.i

.PHONY : src/ZadUnia.i

# target to preprocess a source file
src/ZadUnia.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadUnia.dir/build.make CMakeFiles/ZadUnia.dir/src/ZadUnia.cc.i
.PHONY : src/ZadUnia.cc.i

src/ZadUnia.s: src/ZadUnia.cc.s

.PHONY : src/ZadUnia.s

# target to generate assembly for a file
src/ZadUnia.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadUnia.dir/build.make CMakeFiles/ZadUnia.dir/src/ZadUnia.cc.s
.PHONY : src/ZadUnia.cc.s

src/ZadWywolanieFunkcji.o: src/ZadWywolanieFunkcji.cc.o

.PHONY : src/ZadWywolanieFunkcji.o

# target to build an object file
src/ZadWywolanieFunkcji.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadWywolanieFunkcji.dir/build.make CMakeFiles/ZadWywolanieFunkcji.dir/src/ZadWywolanieFunkcji.cc.o
.PHONY : src/ZadWywolanieFunkcji.cc.o

src/ZadWywolanieFunkcji.i: src/ZadWywolanieFunkcji.cc.i

.PHONY : src/ZadWywolanieFunkcji.i

# target to preprocess a source file
src/ZadWywolanieFunkcji.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadWywolanieFunkcji.dir/build.make CMakeFiles/ZadWywolanieFunkcji.dir/src/ZadWywolanieFunkcji.cc.i
.PHONY : src/ZadWywolanieFunkcji.cc.i

src/ZadWywolanieFunkcji.s: src/ZadWywolanieFunkcji.cc.s

.PHONY : src/ZadWywolanieFunkcji.s

# target to generate assembly for a file
src/ZadWywolanieFunkcji.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadWywolanieFunkcji.dir/build.make CMakeFiles/ZadWywolanieFunkcji.dir/src/ZadWywolanieFunkcji.cc.s
.PHONY : src/ZadWywolanieFunkcji.cc.s

src/ZadZwracanie.o: src/ZadZwracanie.cc.o

.PHONY : src/ZadZwracanie.o

# target to build an object file
src/ZadZwracanie.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadZwracanie.dir/build.make CMakeFiles/ZadZwracanie.dir/src/ZadZwracanie.cc.o
.PHONY : src/ZadZwracanie.cc.o

src/ZadZwracanie.i: src/ZadZwracanie.cc.i

.PHONY : src/ZadZwracanie.i

# target to preprocess a source file
src/ZadZwracanie.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadZwracanie.dir/build.make CMakeFiles/ZadZwracanie.dir/src/ZadZwracanie.cc.i
.PHONY : src/ZadZwracanie.cc.i

src/ZadZwracanie.s: src/ZadZwracanie.cc.s

.PHONY : src/ZadZwracanie.s

# target to generate assembly for a file
src/ZadZwracanie.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ZadZwracanie.dir/build.make CMakeFiles/ZadZwracanie.dir/src/ZadZwracanie.cc.s
.PHONY : src/ZadZwracanie.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ZadAdresowaniePamieci"
	@echo "... ZadArytmetykaWskaznikow"
	@echo "... ZadBin2Dec"
	@echo "... ZadCinCoutFile"
	@echo "... ZadDec2Bin"
	@echo "... ZadIq"
	@echo "... ZadMainExample"
	@echo "... ZadPetle"
	@echo "... ZadPriorytetyOperatorow"
	@echo "... ZadPrzekazywanieTablic"
	@echo "... ZadSwitch"
	@echo "... ZadUnia"
	@echo "... ZadWywolanieFunkcji"
	@echo "... ZadZwracanie"
	@echo "... src/ZadAdresowaniePamieci.o"
	@echo "... src/ZadAdresowaniePamieci.i"
	@echo "... src/ZadAdresowaniePamieci.s"
	@echo "... src/ZadArytmetykaWskaznikow.o"
	@echo "... src/ZadArytmetykaWskaznikow.i"
	@echo "... src/ZadArytmetykaWskaznikow.s"
	@echo "... src/ZadBin2Dec.o"
	@echo "... src/ZadBin2Dec.i"
	@echo "... src/ZadBin2Dec.s"
	@echo "... src/ZadCinCoutFile.o"
	@echo "... src/ZadCinCoutFile.i"
	@echo "... src/ZadCinCoutFile.s"
	@echo "... src/ZadDec2Bin.o"
	@echo "... src/ZadDec2Bin.i"
	@echo "... src/ZadDec2Bin.s"
	@echo "... src/ZadIq.o"
	@echo "... src/ZadIq.i"
	@echo "... src/ZadIq.s"
	@echo "... src/ZadMainExample.o"
	@echo "... src/ZadMainExample.i"
	@echo "... src/ZadMainExample.s"
	@echo "... src/ZadPetle.o"
	@echo "... src/ZadPetle.i"
	@echo "... src/ZadPetle.s"
	@echo "... src/ZadPriorytetyOperatorow.o"
	@echo "... src/ZadPriorytetyOperatorow.i"
	@echo "... src/ZadPriorytetyOperatorow.s"
	@echo "... src/ZadPrzekazywanieTablic.o"
	@echo "... src/ZadPrzekazywanieTablic.i"
	@echo "... src/ZadPrzekazywanieTablic.s"
	@echo "... src/ZadSwitch.o"
	@echo "... src/ZadSwitch.i"
	@echo "... src/ZadSwitch.s"
	@echo "... src/ZadUnia.o"
	@echo "... src/ZadUnia.i"
	@echo "... src/ZadUnia.s"
	@echo "... src/ZadWywolanieFunkcji.o"
	@echo "... src/ZadWywolanieFunkcji.i"
	@echo "... src/ZadWywolanieFunkcji.s"
	@echo "... src/ZadZwracanie.o"
	@echo "... src/ZadZwracanie.i"
	@echo "... src/ZadZwracanie.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

